### ISSUE TITLE
Flutter Web Wrong Output

### ISSUE THREAD

**Issue by Mikailo** [riclava/blake2b#1]
While running the functions 
- hash
-hashHexString2HexString
In flutter web the output is wrong. It is different than the output on android or iOS.

**Comment by riclava** [comment]
can you give the input data?

**Comment by SushantChandla** [comment]
@riclava  https://github.com/dart-lang/sdk/issues/47216 See this issue.

Code:
```
Uint8List publicKey = Uint8List.fromList([92,37,74,216, 114,178,220,105,117,200, 131, 83,238,62,
 121,82, 12,176, 88, 217, 100, 37, 189, 98,155, 103,217, 37,45,213, 143,  135
    ]);
    print("input : $publicKey");
    Uint8List blake2bHash = Blake2bHash.hashWithDigestSize(160, publicKey);
    print("output : $blake2bHash");
```
output in macos(`flutter run -d macos`)
```
flutter: input : [92, 37, 74, 216, 114, 178, 220, 105, 117, 200, 131, 83, 
238, 62, 121, 82, 12, 176, 88, 217, 100, 37, 189, 98, 155, 103, 217, 37, 45,
 213, 143, 135]
flutter: output : [224, 176, 194, 96, 253, 91, 115, 58, 42, 76, 86, 102, 181, 192, 205, 216, 25, 189, 215, 151]
```
output in chrome(`flutter run -d chrome`)
```
input : [92, 37, 74, 216, 114, 178, 220, 105, 117, 200, 131, 83, 238,
62, 121, 82, 12, 176, 88, 217, 100, 37, 189, 98, 155, 103, 217, 37, 45,
213, 143, 135]
output : [185, 198, 8, 29, 12, 136, 243, 75, 182, 78, 71, 211, 231, 85,
36, 182, 84, 74, 206, 206]
```

**Comment by SushantChandla** [comment]
@riclava to fix this issue I have changed from Int64 to BigInt, I thought this would be easy way to fix the issue.
I am not able to understand unsigned right shift implementation  https://github.com/SushantChandla/blake2b/blob/c829a1c3621b858eb53e6e9221abe0493b4d680c/lib/byte_utils.dart#L40

**Comment by riclava** [comment]
OK, let me test it first ;-)

**Comment by riclava** [comment]
thanks a lot~
